name: Create Release and Upload Build

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build darwin-arm64
      run: GOOS=darwin GOARCH=arm64 go build -v -o netfold-${{ github.ref }}-darwin-arm64 .
    - name: Build linux-amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o netfold-${{ github.ref }}-linux-amd64 .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        files: |
          netfold-${{ github.ref }}-darwin-arm64
          netfold-${{ github.ref }}-linux-amd64
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
