name: Publish Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create a release
      uses: action-pack/github-release@v2
      with:
        tag: MyReleaseTag
        title: MyReleaseTitle
        body: MyReleaseMessage
